### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by waveur35** [mgp25/SC-API#242]
Hello,

My proxy was blocked.

Someone know a good non-ban proxy and how to connect to it for send story ?

I've try to edit this line : 

protected $proxyServer = "http://xx.xx.xx.xx:xx:xx:xx";

But now i've error : 

"Warning: First parameter must either be an object or the name of an existing class in C:\inetpub\wwwroot\src\snapchat_agent.php on line 443"

SO I guess my proxy is blacklisted ?

**Comment by waveur35** [comment]
No one can help me with proxy ? ^^" I really don't know how to use and connect to it

**Comment by teknogeek** [comment]
do `$snapchat->setProxyServer("1.2.3.4:5678");` where `1.2.3.4:5678` is your proxy address

**Comment by waveur35** [comment]
thanks a lot, but if my proxy have username and password like 1.2.3.4:80:user:password

it will works ? :)

**Comment by teknogeek** [comment]
no, if you have a username and password it would be `username:password@1.2.3.4:5678`

**Comment by waveur35** [comment]
Perfect, thanks I didn't have error anymore !

I've got this now, it means my VPN is blocked i guess ?

[message] => The network you are connected to has been temporarily blocked because of suspicious activity. If you are connected to a VPN, retry after disconnecting from it. [status] => 403 [logged] => ) RESULT: 1 

thanks tekno n.n

**Comment by teknogeek** [comment]
yes that's correct.

**Comment by waveur35** [comment]
Ok thanks. :D Do you know some website that selling proxy that are not blacklisted by snapchat ? I actually use this IP : 23.95.132.9:80

**Comment by waveur35** [comment]
(sorry for all of my questions)

**Comment by teknogeek** [comment]
uhhh you can try sslprivateproxy.com and ask for proxies for snapchat when
you order but I'm not sure

**Comment by waveur35** [comment]
okey thanks, I will contact them !
