### ISSUE TITLE
Uncaught exception 'CasperException' with message 'API Response: [500] Server Error: null

### ISSUE THREAD

**Issue by waveur35** [mgp25/SC-API#250]
Hello,

I've got this error : 

Fatal error: Uncaught exception 'CasperException' with message 'API Response: [500] Server Error: null StackTrace: java.lang.NullPointerException at com.liamcottle.droidguard.server.server.HttpServer.serve(HttpServer.java:217) at com.liamcottle.droidguard.server.server.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:887) at com.liamcottle.droidguard.server.server.NanoHTTPD$1$1.run(NanoHTTPD.java:158) at java.lang.Thread.run(Thread.java:841) ' in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:178 Stack trace: #0 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true) #1 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAPI.php(92): CasperAgent->post('/snapchat/attes...', NULL, Array) #2 C:\inetpub\wwwroot\src\snapchat.php(151): CasperAPI->getSnapchatAttestation('ypGiPZNqy0iYrQl...') #3 C:\inetpub\wwwroot\src\snapchat.php(362): Snapchat->getAttestation('xxxxx', 'xxxxx', 1446249435043) #4 C:\inetpub\wwwroot\script\all\src\_send.php(57): Snapchat in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 178

Someone know how to solve it ?

**Comment by mgp25** [comment]
@waveur35 retry, it could be an issue server side, but i just test it at works perfectly

Regards
