### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by waveur35** [mgp25/SC-API#252]
Hello.

When I try to send story, I've got this 1/2 time : 

Fatal error: Uncaught exception 'CasperException' with message 'API Response: [500] Server Error: Didn't find class "com.google.ccc.abuse.droidguard.DroidGuard" on path: DexPathList[[zip file "/data/data/com.liamcottle.droidguard.server/cache/dg/dg.apk"],nativeLibraryDirectories=[/data/data/com.liamcottle.droidguard.server/cache/dg/lib, /system/lib]] StackTrace: java.lang.ClassNotFoundException: Didn't find class "com.google.ccc.abuse.droidguard.DroidGuard" on path: DexPathList[[zip file "/data/data/com.liamcottle.droidguard.server/cache/dg/dg.apk"],nativeLibraryDirectories=[/data/data/com.liamcottle.droidguard.server/cache/dg/lib, /system/lib]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) at java.lang.ClassLoader.loadClass(ClassLoader.java:497) at java.lang.ClassLoader.loadClass(ClassLoader.java:457) at com.liamcottle.droidguard.server.server.HttpServer.serve(HttpServer.java:214) at com.liamcottle.droidguard.server.server.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:887) at com.liamcott in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 178

or this error : 

Fatal error: Uncaught exception 'CasperException' with message 'API Response: [503] Attestation Service Unavailable' in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:178 Stack trace: #0 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php(95): CasperAgent->request('/snapchat/attes...', NULL, Array, true) #1 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAPI.php(92): CasperAgent->post('/snapchat/attes...', NULL, Array) #2 C:\inetpub\wwwroot\src\snapchat.php(151): CasperAPI->getSnapchatAttestation('UQxd8pl9qF4bLm9...') #3 C:\inetpub\wwwroot\src\snapchat.php(362): Snapchat->getAttestation('xxxxx', 'xxxxxx', 1446432491002) #4 C:\inetpub\wwwroot\script\all\src\_send.php(58): Snapchat->login('xxxx') #5 C:\inetpub\wwwroot\script\all\lounaxox.php(16): login_snap('xxxx', 'xxxx', 'xxxxx:6n0o5z4...') #6 {main} thrown in C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php on line 178

**Comment by nayanbhana** [comment]
The server was down. Should be fixed now

**Comment by waveur35** [comment]
Error appear again

**Comment by nayanbhana** [comment]
Just read the error: 'API Response: [503] Attestation Service Unavailable'. Obviously the code is fine and the server is down/updating. No need to post another issue about it.
