### ISSUE TITLE
Casper API is being updated

### ISSUE THREAD

**Issue by waveur35** [mgp25/SC-API#258]
Hello,

This error appear since 10 hour.. It's impossible to send any story.

```
Fatal error: Uncaught exception 'CasperException' with message 'External Request Failed!' in
 C:\inetpub\wwwroot\src\Casper-API-PHP\CasperAgent.php:254 Stack trace: #0 C:\inetpub\wwwroot
\src\Casper-API-PHP\CasperAPI.php(84): CasperAgent->externalRequest('https://www.goo...', Array,
 'CiAKBmF0dGVzdBI...', true) #1 C:\inetpub\wwwroot\src\snapchat.php(151): 
CasperAPI->getSnapchatAttestation('IH6JemVRGxC8ngl...') #2 C:\inetpub\wwwroot
\src\snapchat.php(362): Snapchat->getAttestation('XXX', 'XXX', 1447331800019) #3 C:\inetpub
\wwwroot\script\all\src\_send.php(58): Snapchat->login('XXX') #4 C:\inetpub\wwwroot\script
\all\XXX.php(16): login_snap('XXX', 'XXX', 'XXXX:6n0o5z4...') #5 {main} thrown in C:\inetpub\wwwroot
\src\Casper-API-PHP\CasperAgent.php on line 254
```

SOmeone can help me ?

**Comment by liamcottle** [comment]
Google have made some server side changes for security, and until I can figure out how to fix it, nothing will work. Sorry.

**Comment by waveur35** [comment]
Thanks liamcottle ! Hope you will fix it soon ! Good luck :D

**Comment by waveur35** [comment]
Your API have working 3 hour this morning :) ! Thats great

**Comment by mzahlag** [comment]
Worked today but stopped working i hope if you can share login method for blackberry or bluestacks in the php here so all of us can use it

**Comment by liamcottle** [comment]
Keep watch of the Casper Facebook page for proper updates on this problem. I'm still working on a scalable solution, but can't get it running properly yet.

**Comment by HW73** [comment]
@liamcottle thanks for all your work Liam! Look forward to seeing it working again

**Comment by pank123** [comment]
its still not working can you please give us exact time when it will reoslved

**Comment by Chiggins** [comment]
There's no such thing as an exact time with these things. Don't ask.

**Comment by teknogeek** [comment]
Like @Chiggins said, there is no such thing as an exact time. I have put a fix together and it is going to be ready soon.

**Comment by mzahlag** [comment]
wish you luck for all of you please guys donate for this page and subscribe in casper api they truly deserve it

**Comment by LanchaBasualdo** [comment]
Hey @teknogeek I understand Liam's side is down right now. I have a question regarding the ip blocking.
I have tried with DHCP and have still repeatedly get this error: `The network you are connected to has been temporarily blocked because of suspicious activity. If you are connected to a VPN, retry after disconnecting from it.`
Do you have any suggestions on how can I solve this?

**Comment by Chiggins** [comment]
Your DHCP server only gives you addresses in your local network. Your
public IP would be the same.

**Comment by phplab83** [comment]
Fatal error: Uncaught exception 'CasperException' with message 'API Response: [503] Please tap 'Learn More', so you can read the latest post on the Casper Facebook page regarding the current login issues.' 

When it will resolved ?

**Comment by Chiggins** [comment]
Don't ask for a resolve time. When it's fixed, it's fixed. Until then, just
hang tight.

**Comment by mzahlag** [comment]
@LanchaBasualdo have been there before ask your isp to change your ip i fixed it like that

**Comment by mgp25** [comment]
I added a status banner in the readme, that banner shows Casper API status, so when its active again, it will change, so be patient.

**Comment by ZhenhuaJin** [comment]
this api won't work without google authentication?

**Comment by mzahlag** [comment]
Guys i saw in the last few days that casper app was working perfectly for a few moments so there is someone actually trying to fix the login issue but here for casper api github users there is no one trying to fix it at all 
This was the answer when i asked Liam to update the solutions he had found to the api we use 
"Casper App
Casper App Unfortunately there won't be a fix for the GitHub or Public APIs yet"


And I subscribed for unlimited calls to api in casper clients and cant use the api for 1 week or soo for now I deserve the same treatment of casper app users to login 


So please any oneone have an idea how to fix this by our selves please share it i really need to login and finish my project 

btw I respect all of you and im not trying to pick a fight or to low of someone's work i swear no , i just want someone to share any info he can provide to make the login work i realy need it urgently

**Comment by mgp25** [comment]
**Update: ** 18/11/2015 17:00

We are working to fix this soon, please be patient. As soon as we fix it, we will tell here

Regards

_Snapchat API Team_

**Comment by liamcottle** [comment]
We're trying our best! This is just not a fast thing to fix.

We need to acquire a ton of real Android devices to run some custom code, however we're still in the process of getting these devices and setting them up to do the work required for our systems to make logins work.

I can't give an ETA on a fully working fix, as there's still a lot for us to get done.

Cheers.

**Comment by mzahlag** [comment]
@mpg25 @liamcottle god belas you both wish you the best luck

**Comment by homefacts** [comment]
Is this just to mimic what the snapchat does on android?  I'm assuming that snapchat on ios doesn't interact with google to login?

**Comment by hako** [comment]
@homefacts Yes you're right, iOS doesn't need to do this stuff, the android method is the only method that works with the API for now.

**Comment by ZhenhuaJin** [comment]
@hako iOS doesn't need google authentication?

**Comment by mgp25** [comment]
@ZhenhuaJin no, it doesn't. But its harder to reverse engineering while android is easier

**Comment by ZhenhuaJin** [comment]
@mgp25 I have checked snaphack iOS app and they seem to have fixed login issue. when do you think this api will work again?

**Comment by mgp25** [comment]
@ZhenhuaJin _sigh..._ just be patient, we'll tell here when its done

**Comment by liamcottle** [comment]
SnapHack run their own systems, and are not interested in sharing how they do it.

However, I have a fix for Android logins, however it's not scalable enough to release to the public (yet).

Please be patient, while we work on getting a system available for you all to use.

In the meantime, unfortunately there is nothing you can do but wait ;)

**Comment by HW73** [comment]
Thanks for working on the fix, we appreciate the work you guys put in. People need to stop asking for an ETA on when it'll work again

**Comment by sekouperry** [comment]
Thank you guys so much for working on a fix, no matter how long it takes. One of my iOS app relies on your code, so I am at your mercy ;)

**Comment by waveur35** [comment]
Thanks for your work liamcottle
Nobody know an iOS app who works actually for upload pictures ?

**Comment by phplab83** [comment]
Our casper api is still down. you guys are working on it? Because my site is down by this issue.

**Comment by hako** [comment]
@phplab83 The casper API is still under maintenance as said in the [README](https://github.com/mgp25/SC-API). 
Until this has changed. Please be patient.

**Comment by waveur35** [comment]
For people who search something similar, you can use the Snap-Hack apps on iOS, it works perfectly

**Comment by phplab83** [comment]
Any update on casper issue We are still waiting is there any idea when it will resolved?

**Comment by Chiggins** [comment]
@phplab83 You literally just commented on this two days ago asking about this. Announcements will be posted here and on the [Casper](https://www.facebook.com/casper4snapchat/), and you can also look at the [README](https://github.com/mgp25/SC-API). Stop asking.

**Comment by liamcottle** [comment]
For now, you can send `ie` as the `attestation` value in Snapchats login,
instead of requesting it from the Casper and Google servers.

Snapchat have stopped checking it for now.

Cheers.

**Comment by liamcottle** [comment]
For now,

Instead of using the Casper API and Google API to fetch an Attestation, you can send in the Snapchat `/loq/login` request:

```
attestation=ie
```

Snapchat have stopped checking it for now. I can't say how long this will be unchecked, but they have some new Security features in development which are going to kill all of these projects.

So enjoy it while it lasts! :)

Cheers.

**Comment by phplab83** [comment]
@liamcottle snapchat login api is not working without casper can you please give me exact solution for that.?

**Comment by liamcottle** [comment]
I just posted the solution lol

**Comment by liamcottle** [comment]
If you need an example,

Replace the code (in Snapchat.php):

```
public function getAttestation($username, $password, $timestamp){
    $nonce = $this->casper->generateSnapchatNonce($username, $password, $timestamp);
    $attestation = $this->casper->getSnapchatAttestation($nonce);
    return $attestation;
}
```

With:

```
public function getAttestation($username, $password, $timestamp){
    return "ie";
}
```

**Comment by phplab83** [comment]
yes its working fine. But my question is it will work on this way or it will again stop in future ?

**Comment by liamcottle** [comment]
Of course, because Snapchat don't want us to use their API.

There'll always be something that will cause all of this to stop working.

Snapchat have added a new security system into their latest update, (currently experimental), but once it's required, none of these libraries will work anymore.

**Comment by Chiggins** [comment]
Liam, what if you already have an auth token and don't really worry about
having to login through a third party library?

**Comment by liamcottle** [comment]
With Snapchat's new security features (currently being tested), we don't have a problem getting an AuthToken, it's the rest of the API calls that are going to cause trouble...

They're using a new system for the `req_token`, for every API call other than `/loq/login`...

I can't disclose much information about this yet, but once it's required by Snapchat API, we're going to have a lot of problems...

**Comment by robocos987** [comment]
So this is the reason why we cannot log in at the moment?

**Comment by liamcottle** [comment]
You can login, if you make the change to the `snapchat.php` file I posted above :)

**Comment by robocos987** [comment]
Still doesn't work.. :(

**Comment by liamcottle** [comment]
You'll need to open a separate issue, with the debug log etc so we can take a look

**Comment by robocos987** [comment]
Alright

**Comment by robocos987** [comment]
I enabled "less secure settings" and I am still getting the same error..

**Comment by liamcottle** [comment]
@robocos987 Please continue the discussion in the other Issue. This is not related.

**Comment by mgp25** [comment]
Applied quick fix, use latest commit.

Regards

**Comment by liamcottle** [comment]
Cheers, I don't have edit access. So just posted how to fix ;)

**Comment by waveur35** [comment]
Please don't delete my comment this time : Liam, how Snap-Hack have fix the issus ? They use the same fix as you ?

**Comment by liamcottle** [comment]
I'm in a agreement, and can not disclose this information to anyone. Sorry.

**Comment by waveur35** [comment]
Okey thanks no problem, I hope your API and their app will continue to work for a long time

**Comment by mzahlag** [comment]
@liamcottle i really would like to volunteer with  you guys can help you there

**Comment by HW73** [comment]
Works great, videos aren't posting for some reason but that's not a big problem. Cheers guys!

**Comment by ruozi** [comment]
It works yesterday, and now seems that snapchat has fixed the header check.

**Comment by mgp25** [comment]
I dont know why  all of you doesnt keep the auth of the account so you dont need to login again.

Be patient, we know

**Comment by Shun87** [comment]
Can I keep both of google auth token and snapchat auth?

**Comment by HW73** [comment]
Yeah it's not working for me either, that's a shame. Does this mean that this project won't work again, or could there be a workaround?

**Comment by robocos987** [comment]
@HW73 Same here

**Comment by mgp25** [comment]
Dammit, this issue will remain locked 'til the issue is solved. OMG, people you are so so impatient, if you want it so bad, do it yourselves.

Next time keep your auths!
