### ISSUE TITLE
Premium access ?

### ISSUE THREAD

**Issue by waveur35** [mgp25/SC-API#276]
Hello,

liam have speaking about a premium access to the casper API. I think a lot of people here are interested in it, and would pay for it (me included)

Is there anyway to buy a premium access to your API ? Or we need to continue to wait ? :/

Thanks.

**Comment by mgp25** [comment]
Read! Wait! Read again! Im very busy with WhatsApp at the moment, if you wait, there will be easier access to the Snapchat API

**Comment by teknogeek** [comment]
goddamn. why dont people fucking read ever...............
